// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package sqlc

import (
	"context"
)

// iteratorForInsertMessage implements pgx.CopyFromSource.
type iteratorForInsertMessage struct {
	rows                 []InsertMessageParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertMessage) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertMessage) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].Topic,
		r.rows[0].Payload,
	}, nil
}

func (r iteratorForInsertMessage) Err() error {
	return nil
}

func (q *Queries) InsertMessage(ctx context.Context, db DBTX, arg []InsertMessageParams) (int64, error) {
	return db.CopyFrom(ctx, []string{"messages"}, []string{"topic", "payload"}, &iteratorForInsertMessage{rows: arg})
}
