// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acquireMessagesByTopic = `-- name: AcquireMessagesByTopic :many
SELECT
    id, inserted_at, topic, payload
FROM /*tmpl*/ messages /*tmpl*/
WHERE
    topic = $1
LIMIT
    COALESCE($2::integer, 100)
FOR UPDATE SKIP LOCKED
`

type AcquireMessagesByTopicParams struct {
	Topic string      `json:"topic"`
	Limit pgtype.Int4 `json:"limit"`
}

func (q *Queries) AcquireMessagesByTopic(ctx context.Context, db DBTX, arg AcquireMessagesByTopicParams) ([]*Message, error) {
	rows, err := db.Query(ctx, acquireMessagesByTopic, arg.Topic, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.InsertedAt,
			&i.Topic,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteMessagesByIds = `-- name: DeleteMessagesByIds :exec
DELETE FROM /*tmpl*/ messages /*tmpl*/
WHERE
    topic = $1
    AND id = ANY($2::bigint[])
`

type DeleteMessagesByIdsParams struct {
	Topic string  `json:"topic"`
	Ids   []int64 `json:"ids"`
}

func (q *Queries) DeleteMessagesByIds(ctx context.Context, db DBTX, arg DeleteMessagesByIdsParams) error {
	_, err := db.Exec(ctx, deleteMessagesByIds, arg.Topic, arg.Ids)
	return err
}

type InsertMessageParams struct {
	Topic   string `json:"topic"`
	Payload []byte `json:"payload"`
}
